-- Rollback for 0068_s1_revoke_internal_definer_rpcs.sql (NOT auto-applied). GENERATED from the live ACLs that existed before 0068
-- (supabase/tests/gen-acl-rollback.mjs 0068): restores EXACTLY the original EXECUTE grants of PUBLIC / anon / authenticated / service_role on
-- 19 functions - no more, no less. Verified by the preflight ACL diff (supabase/tests/preflight-role-simulation.mjs --rollback).
-- WARNING: this re-opens the update_member_role privilege escalation (anon/authenticated can call it again). Use only briefly.
revoke all on function approve_reservation(uuid) from public, anon, authenticated, service_role;
grant execute on function approve_reservation(uuid) to public;
grant execute on function approve_reservation(uuid) to "anon";
grant execute on function approve_reservation(uuid) to "authenticated";
grant execute on function approve_reservation(uuid) to "service_role";
revoke all on function auto_reassign_reservation_vehicle(uuid,uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function auto_reassign_reservation_vehicle(uuid,uuid,uuid) to "anon";
grant execute on function auto_reassign_reservation_vehicle(uuid,uuid,uuid) to "authenticated";
grant execute on function auto_reassign_reservation_vehicle(uuid,uuid,uuid) to "service_role";
revoke all on function block_vehicle(uuid,text) from public, anon, authenticated, service_role;
grant execute on function block_vehicle(uuid,text) to public;
grant execute on function block_vehicle(uuid,text) to "anon";
grant execute on function block_vehicle(uuid,text) to "authenticated";
grant execute on function block_vehicle(uuid,text) to "service_role";
revoke all on function cancel_reservation(uuid,text) from public, anon, authenticated, service_role;
grant execute on function cancel_reservation(uuid,text) to public;
grant execute on function cancel_reservation(uuid,text) to "anon";
grant execute on function cancel_reservation(uuid,text) to "authenticated";
grant execute on function cancel_reservation(uuid,text) to "service_role";
revoke all on function cancel_workflow_task(uuid) from public, anon, authenticated, service_role;
grant execute on function cancel_workflow_task(uuid) to public;
grant execute on function cancel_workflow_task(uuid) to "anon";
grant execute on function cancel_workflow_task(uuid) to "authenticated";
grant execute on function cancel_workflow_task(uuid) to "service_role";
revoke all on function complete_workflow_task(uuid) from public, anon, authenticated, service_role;
grant execute on function complete_workflow_task(uuid) to public;
grant execute on function complete_workflow_task(uuid) to "anon";
grant execute on function complete_workflow_task(uuid) to "authenticated";
grant execute on function complete_workflow_task(uuid) to "service_role";
revoke all on function create_carpool_participation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid) from public, anon, authenticated, service_role;
grant execute on function create_carpool_participation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid) to "authenticated";
grant execute on function create_carpool_participation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid) to "service_role";
revoke all on function create_vehicle_reservation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid,boolean) from public, anon, authenticated, service_role;
grant execute on function create_vehicle_reservation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid,boolean) to public;
grant execute on function create_vehicle_reservation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid,boolean) to "anon";
grant execute on function create_vehicle_reservation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid,boolean) to "authenticated";
grant execute on function create_vehicle_reservation(timestamp with time zone,timestamp with time zone,text,text,numeric,integer,boolean,text,uuid,boolean) to "service_role";
revoke all on function lock_and_require_multiple_administrators(uuid) from public, anon, authenticated, service_role;
grant execute on function lock_and_require_multiple_administrators(uuid) to "anon";
grant execute on function lock_and_require_multiple_administrators(uuid) to "authenticated";
grant execute on function lock_and_require_multiple_administrators(uuid) to "service_role";
revoke all on function log_audit_event(uuid,uuid,text,text,uuid,jsonb,jsonb) from public, anon, authenticated, service_role;
grant execute on function log_audit_event(uuid,uuid,text,text,uuid,jsonb,jsonb) to "anon";
grant execute on function log_audit_event(uuid,uuid,text,text,uuid,jsonb,jsonb) to "authenticated";
grant execute on function log_audit_event(uuid,uuid,text,text,uuid,jsonb,jsonb) to "service_role";
revoke all on function post_reservation_message(uuid,message_type,text,timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function post_reservation_message(uuid,message_type,text,timestamp with time zone) to public;
grant execute on function post_reservation_message(uuid,message_type,text,timestamp with time zone) to "anon";
grant execute on function post_reservation_message(uuid,message_type,text,timestamp with time zone) to "authenticated";
grant execute on function post_reservation_message(uuid,message_type,text,timestamp with time zone) to "service_role";
revoke all on function record_pickup(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role) from public, anon, authenticated, service_role;
grant execute on function record_pickup(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role) to public;
grant execute on function record_pickup(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role) to "anon";
grant execute on function record_pickup(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role) to "authenticated";
grant execute on function record_pickup(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role) to "service_role";
revoke all on function record_return(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role,text,workflow_task_type[],uuid) from public, anon, authenticated, service_role;
grant execute on function record_return(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role,text,workflow_task_type[],uuid) to public;
grant execute on function record_return(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role,text,workflow_task_type[],uuid) to "anon";
grant execute on function record_return(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role,text,workflow_task_type[],uuid) to "authenticated";
grant execute on function record_return(uuid,integer,numeric,numeric,boolean,text,text[],boolean,boolean,inspection_role,text,workflow_task_type[],uuid) to "service_role";
revoke all on function respond_to_carpool_request(uuid,boolean) from public, anon, authenticated, service_role;
grant execute on function respond_to_carpool_request(uuid,boolean) to "authenticated";
grant execute on function respond_to_carpool_request(uuid,boolean) to "service_role";
revoke all on function rls_auto_enable() from public, anon, authenticated, service_role;
grant execute on function rls_auto_enable() to public;
grant execute on function rls_auto_enable() to "anon";
grant execute on function rls_auto_enable() to "authenticated";
grant execute on function rls_auto_enable() to "service_role";
revoke all on function swap_reservation_vehicle(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function swap_reservation_vehicle(uuid,uuid) to public;
grant execute on function swap_reservation_vehicle(uuid,uuid) to "anon";
grant execute on function swap_reservation_vehicle(uuid,uuid) to "authenticated";
grant execute on function swap_reservation_vehicle(uuid,uuid) to "service_role";
revoke all on function transfer_reservation(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function transfer_reservation(uuid,uuid) to public;
grant execute on function transfer_reservation(uuid,uuid) to "anon";
grant execute on function transfer_reservation(uuid,uuid) to "authenticated";
grant execute on function transfer_reservation(uuid,uuid) to "service_role";
revoke all on function unblock_vehicle(uuid) from public, anon, authenticated, service_role;
grant execute on function unblock_vehicle(uuid) to public;
grant execute on function unblock_vehicle(uuid) to "anon";
grant execute on function unblock_vehicle(uuid) to "authenticated";
grant execute on function unblock_vehicle(uuid) to "service_role";
revoke all on function update_member_role(uuid,uuid,user_role) from public, anon, authenticated, service_role;
grant execute on function update_member_role(uuid,uuid,user_role) to "anon";
grant execute on function update_member_role(uuid,uuid,user_role) to "authenticated";
grant execute on function update_member_role(uuid,uuid,user_role) to "service_role";
