-- Rollback for 0069_l5_revoke_anon_table_privileges.sql (NOT auto-applied). GENERATED from the live ACLs that existed before 0069
-- (supabase/tests/gen-acl-rollback.mjs 0069): restores EXACTLY the table / sequence / column privileges of anon and authenticated on all
-- 25 public relations (including MAINTAIN, sequences and column-level grants). Verified by the preflight ACL diff.
revoke all on table audit_log from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table audit_log to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table audit_log to authenticated;
revoke all on table carpool_events from anon, authenticated;
grant MAINTAIN on table carpool_events to anon;
grant SELECT, MAINTAIN on table carpool_events to authenticated;
revoke all on table carpool_offers from anon, authenticated;
grant MAINTAIN on table carpool_offers to anon;
grant SELECT, MAINTAIN on table carpool_offers to authenticated;
revoke all on table carpool_policy_settings from anon, authenticated;
grant MAINTAIN on table carpool_policy_settings to anon;
grant INSERT, SELECT, MAINTAIN on table carpool_policy_settings to authenticated;
revoke all on table carpool_ride_requests from anon, authenticated;
grant MAINTAIN on table carpool_ride_requests to anon;
grant MAINTAIN on table carpool_ride_requests to authenticated;
grant SELECT ("id") on table carpool_ride_requests to authenticated;
grant SELECT ("organization_id") on table carpool_ride_requests to authenticated;
grant SELECT ("carpool_offer_id") on table carpool_ride_requests to authenticated;
grant SELECT ("rider_id") on table carpool_ride_requests to authenticated;
grant SELECT ("requested_seats") on table carpool_ride_requests to authenticated;
grant SELECT ("requested_departure_at") on table carpool_ride_requests to authenticated;
grant SELECT ("status") on table carpool_ride_requests to authenticated;
grant SELECT ("match_additional_distance_km") on table carpool_ride_requests to authenticated;
grant SELECT ("match_additional_time_min") on table carpool_ride_requests to authenticated;
grant SELECT ("policy_version") on table carpool_ride_requests to authenticated;
grant SELECT ("created_at") on table carpool_ride_requests to authenticated;
grant SELECT ("updated_at") on table carpool_ride_requests to authenticated;
grant SELECT ("responded_at") on table carpool_ride_requests to authenticated;
grant SELECT ("responded_by") on table carpool_ride_requests to authenticated;
grant SELECT ("client_request_id") on table carpool_ride_requests to authenticated;
grant SELECT ("status_reason") on table carpool_ride_requests to authenticated;
revoke all on table carpool_search_log from anon, authenticated;
grant SELECT on table carpool_search_log to authenticated;
revoke all on table chat_conversations from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table chat_conversations to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table chat_conversations to authenticated;
revoke all on table chat_messages from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table chat_messages to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table chat_messages to authenticated;
revoke all on table corporate_mobility_points from anon, authenticated;
grant MAINTAIN on table corporate_mobility_points to anon;
grant INSERT, SELECT, UPDATE, DELETE, MAINTAIN on table corporate_mobility_points to authenticated;
revoke all on table geo_provider_quota_counters from anon, authenticated;
grant MAINTAIN on table geo_provider_quota_counters to anon;
grant SELECT, MAINTAIN on table geo_provider_quota_counters to authenticated;
revoke all on table inspection_photos from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table inspection_photos to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table inspection_photos to authenticated;
revoke all on table inspections from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table inspections to authenticated;
revoke all on table notifications from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table notifications to authenticated;
revoke all on table organization_settings from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table organization_settings to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table organization_settings to authenticated;
revoke all on table organizations from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table organizations to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table organizations to authenticated;
revoke all on table profiles from anon, authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table profiles to authenticated;
grant SELECT ("id") on table profiles to authenticated;
grant SELECT ("organization_id") on table profiles to authenticated;
grant SELECT ("full_name") on table profiles to authenticated;
grant SELECT ("role") on table profiles to authenticated;
grant SELECT ("created_at") on table profiles to authenticated;
grant SELECT ("avatar_url") on table profiles to authenticated;
grant SELECT ("gantt_zoom_preference") on table profiles to authenticated;
revoke all on table reservation_messages from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table reservation_messages to authenticated;
revoke all on table reservations from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table reservations to authenticated;
revoke all on table safety_equipment_items from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table safety_equipment_items to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table safety_equipment_items to authenticated;
revoke all on table trip_participants from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table trip_participants to authenticated;
revoke all on table trip_requests from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table trip_requests to authenticated;
revoke all on table vehicle_categories from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicle_categories to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicle_categories to authenticated;
revoke all on table vehicle_locations from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicle_locations to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicle_locations to authenticated;
revoke all on table vehicles from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicles to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table vehicles to authenticated;
revoke all on table workflow_tasks from anon, authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table workflow_tasks to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table workflow_tasks to authenticated;
